INSERT INTO PORT VALUES (1, 'DUBLIN');
INSERT INTO PORT VALUES (2, 'STOCKHOLM');
INSERT INTO PORT VALUES (3, 'NEW YORK');
INSERT INTO PORT VALUES (4, 'MELBOURNE');

INSERT INTO CARGO VALUES (1, 1, 2);
INSERT INTO CARGO VALUES (2, 3, 4);
